name: lianes-library
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - streamlit=1.53.1
  - sqlalchemy
  - matplotlib
  - beautifulsoup4
  - ipykernel
  - requests
  - pymysql
  - cryptography
  - pyarrow
  - openpyxl
  - lxml
  - tqdm
  - notebook
  - jupyterlab
  - pytest
  - pip
  # pip-only packages
  - pip:
    - langchain==0.1.20
    - langchain-huggingface
    - langchain-core
    - sentence-transformers==3.0.1
    - chromadb==0.4.24
    - huggingface_hub
